export const Images = {
    ADD_CAR: require('./../../assets/images/add-car-icon.png'),
    APP_LOGO: require('./../../assets/images/app-logo.png'),
    ARROW_LEFT: require('./../../assets/images/arrow-right.png'),
    BACK_ARROW_WHITE: require('./../../assets/images/back-arrow-white.png'),
    BACK_ARROW_BLACK: require('./../../assets/images/back-arrow-black.png'),
    BASKET_BLACK: require('./../../assets/images/basket-icon-black.png'),
    CART_BLACK: require('./../../assets/images/cart-icon-black.png'),
    CART_GREY: require('./../../assets/images/cart-icon-grey.png'),
    CASH_ON_DELIVERY: require('./../../assets/images/cash_on_delivery.png'),
    COUNT_ARROW_DOWN: require('./../../assets/images/count-arrow-down.png'),
    COUNT_ARROW_UP: require('./../../assets/images/count-arrow-up.png'),
    FAVORITES_ICON: require('./../../assets/images/favorites-icon.png'),
    FILTER_ICON: require('./../../assets/images/filter-icon.png'),
    FLAG_US: require('./../../assets/images/flag-us.png'),
    FLAG_GEO: require('./../../assets/images/flag-geo.png'),
    FLAG_RU: require('./../../assets/images/flag-ru.png'),
    HEART_YELLOW: require('./../../assets/images/favorites-yellow.png'),
    HOME_TAB_BLACK: require('./../../assets/images/hometab-icon-black.png'),
    HOME_TAB_GREY:  require('./../../assets/images/hometab-icon-grey.png'),
    LANGUAGE_ICON: require('./../../assets/images/chose-language.png'),
    LOGOUT_ICON: require('./../../assets/images/logout-icon.png'),
    LOCATION_ICON: require('./../../assets/images/location-icon.png'),
    NO_IMAGE: require('./../../assets/images/noimage-icon.png'),
    PRODUCT_BLACK: require('./../../assets/images/products-icon-black.png'),
    PRODUCT_GREY: require('./../../assets/images/products-icon-grey.png'),
    PROFILE_BLACK: require('./../../assets/images/profile-icon-black.png'),
    PROFILE_GREY: require('./../../assets/images/profile-icon-grey.png'),
    SEARCH_BLACK: require('./../../assets/images/search-icon-black.png'),
    SEARCH_GREY: require('./../../assets/images/search-icon-gray.png'),
    TECH_SUPPORT: require('./../../assets/images/tech-support.png'),
    WALL_CLOCK: require('./../../assets/images/wall-clock.png')

}